### ISSUE TITLE
Crossplay support

### ISSUE THREAD

**Issue by ZiecikMarcin** [Chris-D-Turk/Valheim.Google.Cloud#1]
Hi! I'm trying to configure a server from this guide, but I can't find a way to make it run new -crossplay param. Could you help please?

**Comment by Chris-D-Turk** [comment]
Hi @ZiecikMarcin I also just tried the new -crossplay param - without success unfortunately. The dedicated server just crashes with the following message 
> start_server_custom.sh: line 60:  9456 Segmentation fault      ./valheim_server.x86_64 -name "$server_name" -port 2456 -world "$world_name" -crossplay -password "$server_password"

Others have the same problem:
https://www.reddit.com/r/valheim/comments/xpw0b5/valheim_server_disconnected_from_playfab/
https://steamcommunity.com/app/892970/discussions/1/3373782977091683705/

Irongate is working on a fix: 
https://valheimbugs.featureupvote.com/suggestions/334024/crossplay-patch-prevents-dedicated-linux-servers-from-starting

As a hotfix you could delete the failing library and remove the -crossplay param:
`rm valheim_server_Data/Plugins/libparty.so`
Alternatively (if you really need Crossplay) you could try other Linux distributions (the issue seems to be related to Debian)

Some additional notes for future reference:
- The failure occurred after installing libpulse-dev (before I just couldn't connect) - see https://www.reddit.com/r/valheim/comments/xpw0b5/comment/irlz5ig/?utm_source=share&utm_medium=web2x&context=3
- After installing this lib the server crashes even without the -crossplay flag

**Comment by Chris-D-Turk** [comment]
updated guide for crossplay
